[package]
name = "simple-physics"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]

[dependencies]
best = "0.12"
cgmath = "0.16"
fnv = "1.0"
gfx = "0.17"
gfx_device_gl = "0.15"
gfx_window_glutin = "0.23"
glutin = "0.15"
